📚 Feature/readme
SimformSolutionsPvtLtd/flutter_empty_placeholder_view pull request #3
Opened 2022-08-28 14:39 UTC by ShwetaChauhan18

- 📚 Feature/readme

2022-09-13 06:55 UTC, vatsaltanna commented on README.md
> +* __[spinkit](https://pub.dev/packages/flutter_spinkit)__
few other libraries are missing here

2022-09-15 09:01 UTC, AnkitSimform commented on README.md
> +Methods defined by `SSPlaceholder` class:
Can we merge the row for the section title?

2022-11-18 10:12 UTC, HappyMakadiyaS commented on README.md
> +<img src="https://github.com/SimformSolutionsPvtLtd/flutter_ss_placeholder_view/blob/feature/readme/preview/placeholderview.gif" width="400" height="711">
Provide master branch url instead of feature/readme branch.

2022-11-18 12:18 UTC, HappyMakadiyaS requested changes

2022-11-18 12:18 UTC, HappyMakadiyaS commented on README.md
> +Methods defined by `SSPlaceholder` class:
^^
Ref: https://stackoverflow.com/a/61997043/19938097

2022-11-18 12:18 UTC, HappyMakadiyaS commented on example/lib/mail_page.dart
> +  void _clearData() {
convert to expression body

2022-11-18 12:18 UTC, HappyMakadiyaS commented on example/lib/mail_page.dart
> +      placeholderWidget = null;
Can be convert into switch case

2022-11-18 12:18 UTC, HappyMakadiyaS commented on example/lib/main.dart
> +        body: Builder(builder: (context) => const MailPage()),
Builder can be removed.

2022-11-18 12:18 UTC, HappyMakadiyaS commented on example/lib/mail_page.dart
> +                  placeholderWidget: placeholderWidget,
Can't we remove the placeholder keyword from the parameter name? as class name itself indicating that its configuration of Placeholder

2022-11-18 12:18 UTC, HappyMakadiyaS commented on example/lib/mail_page.dart
> +                  loadingSubtitle: 'Loading your data...',
^^

2022-11-18 12:18 UTC, HappyMakadiyaS commented on lib/src/vector_asset.dart
> +            : Image.asset('');
Can we use Sizedbox.shrink()?

2022-11-18 12:19 UTC, HappyMakadiyaS commented
Also suggesting you to update PR title and branch name.

2022-11-18 14:59 UTC, HappyMakadiyaS reviewed
LGTM

2022-11-21 04:32 UTC, closed without merging